// Generated by gencpp from file xbox/marine.msg
// DO NOT EDIT!


#ifndef XBOX_MESSAGE_MARINE_H
#define XBOX_MESSAGE_MARINE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xbox
{
template <class ContainerAllocator>
struct marine_
{
  typedef marine_<ContainerAllocator> Type;

  marine_()
    : thl(0.0)
    , strm(0.0)  {
    }
  marine_(const ContainerAllocator& _alloc)
    : thl(0.0)
    , strm(0.0)  {
  (void)_alloc;
    }



   typedef float _thl_type;
  _thl_type thl;

   typedef float _strm_type;
  _strm_type strm;





  typedef boost::shared_ptr< ::xbox::marine_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xbox::marine_<ContainerAllocator> const> ConstPtr;

}; // struct marine_

typedef ::xbox::marine_<std::allocator<void> > marine;

typedef boost::shared_ptr< ::xbox::marine > marinePtr;
typedef boost::shared_ptr< ::xbox::marine const> marineConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xbox::marine_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xbox::marine_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::xbox::marine_<ContainerAllocator1> & lhs, const ::xbox::marine_<ContainerAllocator2> & rhs)
{
  return lhs.thl == rhs.thl &&
    lhs.strm == rhs.strm;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::xbox::marine_<ContainerAllocator1> & lhs, const ::xbox::marine_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace xbox

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::xbox::marine_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xbox::marine_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xbox::marine_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xbox::marine_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xbox::marine_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xbox::marine_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xbox::marine_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e8ddfec22a5ef4b813c4ad7dee7890ed";
  }

  static const char* value(const ::xbox::marine_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe8ddfec22a5ef4b8ULL;
  static const uint64_t static_value2 = 0x13c4ad7dee7890edULL;
};

template<class ContainerAllocator>
struct DataType< ::xbox::marine_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xbox/marine";
  }

  static const char* value(const ::xbox::marine_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xbox::marine_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Message file for marine commands\n"
"\n"
"float32 thl	#controls the throttle\n"
"float32 strm	#controls the waterjet nozzle\n"
;
  }

  static const char* value(const ::xbox::marine_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xbox::marine_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.thl);
      stream.next(m.strm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct marine_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xbox::marine_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xbox::marine_<ContainerAllocator>& v)
  {
    s << indent << "thl: ";
    Printer<float>::stream(s, indent + "  ", v.thl);
    s << indent << "strm: ";
    Printer<float>::stream(s, indent + "  ", v.strm);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XBOX_MESSAGE_MARINE_H
