// Generated by gencpp from file xbee/auto_ctrl.msg
// DO NOT EDIT!


#ifndef XBEE_MESSAGE_AUTO_CTRL_H
#define XBEE_MESSAGE_AUTO_CTRL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xbee
{
template <class ContainerAllocator>
struct auto_ctrl_
{
  typedef auto_ctrl_<ContainerAllocator> Type;

  auto_ctrl_()
    : auto_ctrls()  {
      auto_ctrls.assign(0);
  }
  auto_ctrl_(const ContainerAllocator& _alloc)
    : auto_ctrls()  {
  (void)_alloc;
      auto_ctrls.assign(0);
  }



   typedef boost::array<uint8_t, 16>  _auto_ctrls_type;
  _auto_ctrls_type auto_ctrls;





  typedef boost::shared_ptr< ::xbee::auto_ctrl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xbee::auto_ctrl_<ContainerAllocator> const> ConstPtr;

}; // struct auto_ctrl_

typedef ::xbee::auto_ctrl_<std::allocator<void> > auto_ctrl;

typedef boost::shared_ptr< ::xbee::auto_ctrl > auto_ctrlPtr;
typedef boost::shared_ptr< ::xbee::auto_ctrl const> auto_ctrlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xbee::auto_ctrl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xbee::auto_ctrl_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::xbee::auto_ctrl_<ContainerAllocator1> & lhs, const ::xbee::auto_ctrl_<ContainerAllocator2> & rhs)
{
  return lhs.auto_ctrls == rhs.auto_ctrls;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::xbee::auto_ctrl_<ContainerAllocator1> & lhs, const ::xbee::auto_ctrl_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace xbee

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::xbee::auto_ctrl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xbee::auto_ctrl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xbee::auto_ctrl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xbee::auto_ctrl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xbee::auto_ctrl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xbee::auto_ctrl_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xbee::auto_ctrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9d019e319a4cd95831863d035d7d77d8";
  }

  static const char* value(const ::xbee::auto_ctrl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9d019e319a4cd958ULL;
  static const uint64_t static_value2 = 0x31863d035d7d77d8ULL;
};

template<class ContainerAllocator>
struct DataType< ::xbee::auto_ctrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xbee/auto_ctrl";
  }

  static const char* value(const ::xbee::auto_ctrl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xbee::auto_ctrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Message where each sub command from simulink or trigger script for the MQS is published into\n"
"\n"
"uint8[16] auto_ctrls\n"
;
  }

  static const char* value(const ::xbee::auto_ctrl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xbee::auto_ctrl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.auto_ctrls);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct auto_ctrl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xbee::auto_ctrl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xbee::auto_ctrl_<ContainerAllocator>& v)
  {
    s << indent << "auto_ctrls[]" << std::endl;
    for (size_t i = 0; i < v.auto_ctrls.size(); ++i)
    {
      s << indent << "  auto_ctrls[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.auto_ctrls[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // XBEE_MESSAGE_AUTO_CTRL_H
