// Generated by gencpp from file xbee/cmd_ctrl.msg
// DO NOT EDIT!


#ifndef XBEE_MESSAGE_CMD_CTRL_H
#define XBEE_MESSAGE_CMD_CTRL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xbee
{
template <class ContainerAllocator>
struct cmd_ctrl_
{
  typedef cmd_ctrl_<ContainerAllocator> Type;

  cmd_ctrl_()
    : cmds()  {
      cmds.assign(0);
  }
  cmd_ctrl_(const ContainerAllocator& _alloc)
    : cmds()  {
  (void)_alloc;
      cmds.assign(0);
  }



   typedef boost::array<uint8_t, 16>  _cmds_type;
  _cmds_type cmds;





  typedef boost::shared_ptr< ::xbee::cmd_ctrl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xbee::cmd_ctrl_<ContainerAllocator> const> ConstPtr;

}; // struct cmd_ctrl_

typedef ::xbee::cmd_ctrl_<std::allocator<void> > cmd_ctrl;

typedef boost::shared_ptr< ::xbee::cmd_ctrl > cmd_ctrlPtr;
typedef boost::shared_ptr< ::xbee::cmd_ctrl const> cmd_ctrlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xbee::cmd_ctrl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xbee::cmd_ctrl_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::xbee::cmd_ctrl_<ContainerAllocator1> & lhs, const ::xbee::cmd_ctrl_<ContainerAllocator2> & rhs)
{
  return lhs.cmds == rhs.cmds;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::xbee::cmd_ctrl_<ContainerAllocator1> & lhs, const ::xbee::cmd_ctrl_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace xbee

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::xbee::cmd_ctrl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xbee::cmd_ctrl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xbee::cmd_ctrl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xbee::cmd_ctrl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xbee::cmd_ctrl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xbee::cmd_ctrl_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xbee::cmd_ctrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "65c47160f0c57a1a6dca334e2e8b2754";
  }

  static const char* value(const ::xbee::cmd_ctrl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x65c47160f0c57a1aULL;
  static const uint64_t static_value2 = 0x6dca334e2e8b2754ULL;
};

template<class ContainerAllocator>
struct DataType< ::xbee::cmd_ctrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xbee/cmd_ctrl";
  }

  static const char* value(const ::xbee::cmd_ctrl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xbee::cmd_ctrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Message where each sub command message for the MQS is published into\n"
"\n"
"uint8[16] cmds\n"
;
  }

  static const char* value(const ::xbee::cmd_ctrl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xbee::cmd_ctrl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmds);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cmd_ctrl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xbee::cmd_ctrl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xbee::cmd_ctrl_<ContainerAllocator>& v)
  {
    s << indent << "cmds[]" << std::endl;
    for (size_t i = 0; i < v.cmds.size(); ++i)
    {
      s << indent << "  cmds[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.cmds[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // XBEE_MESSAGE_CMD_CTRL_H
